[package]
name = "sqc"
version = "0.2.1"
edition = "2021"

description = "SQL queries for collections"
homepage = "https://github.com/Anexen/sqc"
keywords = ["python", "linq", "sql", "query-engine"]
license = "MIT"
readme = "README.md"

[lib]
name = "sqc"
crate-type = ["cdylib", "rlib"]

[dependencies]
derive_more = { version = "0.99", default-features = false, features = ["display", "from", "error"] }
fxhash = "0.2"
indexmap = "2"
itertools = "0.13"
pyo3 = { version = "0.22", features = ["indexmap"] }
sqlparser = "0.48"

[dev-dependencies]
pyo3 = { version = "0.22", features = ["auto-initialize"] }
rstest = "0.21"

[profile.release]
opt-level = 3
debug = false
lto = true
codegen-units = 1
